# Generated by Django 3.2.2 on 2021-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body_text',
        ),
        migrations.AddField(
            model_name='page',
            name='bodytext',
            field=models.TextField(blank=True, verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(verbose_name='Last Updated'),
        ),
    ]
