# Generated by Django 4.1.2 on 2022-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User name')),
                ('date', models.DateField(auto_now=True, verbose_name='Updated date')),
                ('permalink', models.URLField(max_length=20, unique=True, verbose_name='Paragraph Link')),
                ('body', models.TextField(verbose_name='Body Text')),
            ],
        ),
    ]
