# Generated by Django 4.1.2 on 2022-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='permalink',
            field=models.CharField(max_length=56, unique=True, verbose_name='Paragraph Link'),
        ),
    ]
