# Generated by Django 3.2.2 on 2021-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Date_of_Current',
            field=models.DateField(auto_now_add=True),
        ),
    ]
