# Generated by Django 3.2.2 on 2021-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_record', '0005_alter_record_date_of_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Date_of_Current',
            field=models.DateField(null=True, verbose_name='Last Added'),
        ),
    ]
