# Generated by Django 3.1.1 on 2021-11-18 05:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('gender', models.TextField(choices=[('MA', 'Male'), ('FMA', 'Female'), ('TG', 'Transgender')], default='MA', max_length=3)),
                ('age', models.IntegerField(default=18)),
                ('date_of_checkup', models.DateField(default=datetime.datetime(2021, 11, 18, 5, 52, 53, 477523, tzinfo=utc))),
                ('address', models.TextField()),
                ('presenting_complaint', models.CharField(max_length=255)),
                ('history_of_presenting_complaint', models.TextField()),
                ('systemic_inquiry', models.TextField()),
                ('past_medical_history', models.CharField(max_length=50)),
                ('past_surgical_history', models.CharField(max_length=50, verbose_name='Past Surgical History')),
                ('drug_history', models.CharField(max_length=255, verbose_name='Drug History')),
                ('allergies', models.CharField(max_length=50, verbose_name='Allergies')),
                ('travel_history', models.CharField(max_length=255, verbose_name='Travel History')),
                ('blood_transfusion_history', models.CharField(default=None, max_length=50)),
                ('sexual_history', models.CharField(default=None, max_length=50)),
                ('cns_examination', models.CharField(max_length=255)),
                ('general_physical_examination', models.CharField(max_length=255)),
                ('higher_mental_functions', models.TextField()),
                ('cranial_nerves', models.TextField(verbose_name='Cranial Nerves')),
                ('motor_system', models.TextField(verbose_name='Motor System')),
                ('sensory_system', models.TextField(verbose_name='sensory System')),
                ('cerebellum', models.CharField(max_length=255)),
                ('somi', models.CharField(max_length=255)),
                ('gait', models.CharField(max_length=255)),
                ('back_tenderness', models.CharField(max_length=255)),
                ('doctor_attending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
