# Generated by Django 4.1.3 on 2022-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email.')),
                ('feedback', models.TextField(verbose_name='Write your feedback.')),
            ],
        ),
    ]
