# Generated by Django 4.1.2 on 2022-12-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_feedbackpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
