# Generated by Django 3.2.10 on 2022-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='cnic',
            field=models.PositiveSmallIntegerField(verbose_name='Enter your CNIC.'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.PositiveSmallIntegerField(verbose_name='Enter your phone number, 11 digits only.'),
        ),
    ]
