# Generated by Django 4.0.2 on 2022-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.IntegerField()),
                ('debtAmount', models.IntegerField()),
                ('debtDate', models.DateField()),
            ],
        ),
    ]
