# Generated by Django 4.0.2 on 2022-03-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
