# Generated by Django 4.0.2 on 2022-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notif_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
