# Generated by Django 4.1.3 on 2022-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
